#!/bin/sh

cd /tmp/ #到/tmp/目录下
xhost + #设置X11权限
vglclient &
expect make_docker.ep $1 $2 $3 $4 $5 $6 #执行创建docker指令，与docker交互
sleep 2s
expect start_temp_docker.ep $1 $2 $3 $4 $5 $6
expect delete_docker.ep $1 $2 $3 ${4}"_temp"
vglclient -kill
exit


